behaviors:
  EnemyBehaviorHard:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 100000
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 5000
