behaviors:
  EnemyBehaviorHard:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 100000
      learning_rate: 0.001
      beta: 0.005
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2000000
    time_horizon: 128
    summary_freq: 10000
